package MedicalChat.app.enums;

public enum TipoEspecialidad {
    CARDIOLOGIA, DERMATOLOGIA, GASTROENTEROLOGIA, GERIATRIA, GENETICA, HEMATOLOGIA, INFECTOLOGIA, INMUNOLOGIA, NEUMOLOGIA, NEUROLOGIA, NUTRIOLOGIA, ONCOLOGIA, PEDIATRIA, PSIQUIATRIA, TOXICOLOGIA
}
